### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by pachuco** [Ckath/ini_rw#1]
1. "#include <linux/limits.h>" doesn't seem to be used and prevents compiling on windows. Can be removed.
2. GCC warns that current_section may be uninitilized at this point.
https://github.com/Ckath/ini_rw/blob/20b811b11ce0eb9f3a9db65bf30a1b1015adff2a/ini_rw.c#L275

**Comment by Ckath** [comment]
going to be very lackluster answers to these I'm afraid, but fair point I shouldve worded it in the readme it was like this:
1. only ever tested and used on linux, the limits include provides `PATH_MAX`.
2. given a valid ini file it will never be unitilized as that section is set on finding the first one. there is pretty much no handling for invalid ini files anywhere to begin with

I'll get to these eventually, probably: 

- [x] stop using linux/limits.h
- [x] handle (or mention lack thereof) invalid ini format cases.

**Comment by Ckath** [comment]
I've just initialized these to `NULL` for now, should all be fine functionally.
